apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: millennium-frontend
  namespace: millennium-frontend
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: millennium-frontend
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: millennium-frontend
  namespace: millennium-frontend
spec:
  selector:
    app:  millennium-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: millennium-frontend-deployment
  namespace: millennium-frontend
spec:
  selector:
    matchLabels:
      app: millennium-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: millennium-frontend
    spec:
      containers:
      - name: millennium-frontend
        image: gusbell/millennium-frontend:1.0.0
        ports:
        - containerPort: 4173