apiVersion: v1
kind: ConfigMap
metadata:
  name: millennium-frontend
  namespace: millennium-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: millennium-frontend-ingress
  namespace: millennium-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: millennium-frontend-service
                port:
                  number: 80
                  targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: millennium-frontend-service
  namespace: millennium-frontend
spec:
  selector:
    app: millennium-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: millennium-frontend-deployment
  namespace: millennium-frontend
  labels:
    app: millennium-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: millennium-frontend
  template:
    metadata:
      labels:
        app: millennium-frontend
    spec:
      containers:
        - name: millennium-frontend
          image: millennium-frontend:latest
          ports:
            - containerPort: 80